import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";
import challenge_18 from "../public/challenge_18.gif";
import challenge_19 from "../public/challenge_19.gif";
import challenge_12 from "../public/challenge_12.png";
import challenge_5 from "../public/challenge_5.png";
import challenge_3 from "../public/challenge_3.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen py-5">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Grant Williamson</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Grant Williamson
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Coding bootcamp student showing off my projects!
            </p>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <h1>NOSQL Social Network API</h1>
              <a href={"https://github.com/grant5622/Challenge_18"} target="_blank" rel="noopener noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={challenge_18}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <h1>Progressive Web Applications (PWA): Text Editor</h1>
              <a href={"https://github.com/grant5622/Challenge_19"} target="_blank" rel="noopener noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={challenge_19}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <h1>SQL Employee Tracker</h1>
              <a href={"https://github.com/grant5622/Challenge_12/tree/main/Challenge_12/02-Challenge"} target="_blank" rel="noopener noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={challenge_12}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <h1>Daily Note Calender</h1>
              <a href={"https://github.com/grant5622/Challenge_05"} target="_blank" rel="noopener noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={challenge_5}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <h1>Password Generator</h1>
              <a href={"https://github.com/grant5622/Challenge_03"} target="_blank" rel="noopener noreferrer">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={challenge_3}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
